name: Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Config
        run: |
          git config --global user.email "ci@github.com"
          git config --global user.name "CI user"
      - name: Install
        run: npm ci
      - name: Build
        env:
          NODE_APP_INSTANCE: podlovers
        run: npm run build
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PODLOVERS_FRONTEND }}'
          projectId: podlovers-frontend
          channelId: live
